image: Visual Studio 2019
init:
  - git config --global core.autocrlf input
before_build:
  - ps: >-
      $buildId = $env:APPVEYOR_BUILD_NUMBER.PadLeft(5, '0');
      $versionSuffixPR = "-PR$($env:APPVEYOR_PULL_REQUEST_NUMBER)-$buildId";
      $branchName = "$env:APPVEYOR_REPO_BRANCH".Replace("_","");
      $versionSuffixBRANCH = "-$branchName-$buildId";
      $env:VersionSuffix = if ("$env:APPVEYOR_REPO_TAG" -eq "true") { "" } else { if ("$env:APPVEYOR_PULL_REQUEST_NUMBER") { $versionSuffixPR } else { $versionSuffixBRANCH } };
install:
  - cmd: choco install dotnetcore-sdk -y
build_script:
  - cmd: echo vs %VersionSuffix%"
  - cmd: build.cmd All
  - cmd: dotnet pack -c Release
test: off
version: 0.0.1.{build}
artifacts:
  - path: bin
    name: bin
  - path: 'src\**\*.nupkg'
    name: nupkgs
branches:
  only:
  - master
